import { Router } from 'express';
import { asyncHandler } from '../../middleware/asyncHandler.js';
import { requireAuth } from '../../middleware/requireAuth.js';
import { requireRole } from '../../middleware/requireRole.js';
import { accountController, bookSlotController, cancelBookingController, changePasswordController, driveSlotsController, interviewsController, offersController, portalController, respondOfferController, revealRequestsController, respondRevealController, updateAccountController } from './seekerPortal.controller.js';

export const seekerPortalRoutes = Router();
seekerPortalRoutes.use(requireAuth);
seekerPortalRoutes.use(requireRole('jobseeker'));
seekerPortalRoutes.get('/portal', asyncHandler(portalController));
seekerPortalRoutes.get('/portal/reveal-requests', asyncHandler(revealRequestsController));
seekerPortalRoutes.post('/portal/reveal-requests/:applicationId/respond', asyncHandler(respondRevealController));
seekerPortalRoutes.get('/portal/interviews', asyncHandler(interviewsController));
seekerPortalRoutes.get('/portal/offers', asyncHandler(offersController));
seekerPortalRoutes.post('/portal/offers/:applicationId/respond', asyncHandler(respondOfferController));
seekerPortalRoutes.get('/portal/account', asyncHandler(accountController));
seekerPortalRoutes.patch('/portal/account', asyncHandler(updateAccountController));
seekerPortalRoutes.post('/portal/account/password', asyncHandler(changePasswordController));
seekerPortalRoutes.get('/portal/drives/:driveId/slots', asyncHandler(driveSlotsController));
seekerPortalRoutes.post('/portal/slots/:slotId/book', asyncHandler(bookSlotController));
seekerPortalRoutes.delete('/portal/slots/:slotId/book', asyncHandler(cancelBookingController));
